import { Josefin_Sans } from "next/font/google";
import "./globals.css";

const josefin_Sans = Josefin_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={josefin_Sans.className}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
